-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 14:31:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema indeed_jobs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema indeed_jobs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indeed_jobs` DEFAULT CHARACTER SET utf8 ;
USE `indeed_jobs` ;

-- -----------------------------------------------------
-- Table `indeed_jobs`.`job_descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indeed_jobs`.`job_descriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `indeed_link` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(20000) NOT NULL,
  `indeed_title` VARCHAR(100) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `location` VARCHAR(100) NULL,
  UNIQUE INDEX `indeed_link_UNIQUE` (`indeed_link` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indeed_jobs`.`tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indeed_jobs`.`tools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tool` VARCHAR(45) NOT NULL,
  `tool_group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tool_UNIQUE` (`tool` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indeed_jobs`.`job_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `indeed_jobs`.`job_requirements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NOT NULL,
  `tool_id` INT NOT NULL,
  INDEX `fk_job_requirements_job_descriptions1_idx` (`job_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_job_requirements_tools1_idx` (`tool_id` ASC) VISIBLE,
  CONSTRAINT `fk_job_requirements_job_descriptions1`
    FOREIGN KEY (`job_id`)
    REFERENCES `indeed_jobs`.`job_descriptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_requirements_tools1`
    FOREIGN KEY (`tool_id`)
    REFERENCES `indeed_jobs`.`tools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
