USE indeed_jobs;

INSERT INTO 
	tools(tool, tool_group) 
VALUES 
	('python', 'Linguagem'),
    ('r', 'Linguagem'),
    ('sql', 'Linguagem'),
    ('java', 'Linguagem'),
    ('scala', 'Linguagem'),
    ('nosql', 'Linguagem'),
    ('sas', 'Linguagem'),
    ('go', 'Linguagem'),
    ('c++', 'Linguagem'),
    ('javascript', 'Linguagem'),
    ('tableau', 'Ferramentas'),
    ('excell', 'Ferramentas'),
    ('power bi', 'Ferramentas'),
    ('qlik', 'Ferramentas'),
    ('looker', 'Ferramentas'),
    ('alteryx', 'Ferramentas'),
    ('mysql', 'Database'),
    ('cassandra', 'Database'),
	('postgresql', 'Database'),
    ('mongodb', 'Database'),
	('elasticsearch', 'Database'),
    ('dynamodb', 'Database'),
    ('db2', 'Database'),
	('redis', 'Database'),
    ('neo4j', 'Database'),
    ('sql server', 'Database'),
	('sqlite', 'Database'),
    ('mariadb', 'Database'),
    ('aws', 'Cloud'),
    ('azure', 'Cloud'),
    ('gcp', 'Cloud'),
    ('snowflake', 'Cloud'),
    ('oracle', 'Cloud'),
    ('databrics', 'Cloud'),
    ('bigquery', 'Cloud'),
    ('redshift', 'Cloud'),
    ('spark', 'Bibliotecas'),
    ('pyspark', 'Bibliotecas'),
    ('hadoop', 'Bibliotecas'),
    ('pandas', 'Bibliotecas'),
    ('airflow', 'Bibliotecas'),
    ('kafka', 'Bibliotecas'),
    ('tensorflow', 'Bibliotecas'),
    ('pytorch', 'Bibliotecas'),
    ('keras', 'Bibliotecas'),
    ('scikit-learn', 'Bibliotecas'),
    ('jupyter', 'Bibliotecas'),
    ('numpy', 'Bibliotecas'),
    ('plotly', 'Bibliotecas'),
    ('seaborn', 'Bibliotecas'),
    ('spacy', 'Bibliotecas'),
    ('matplotlib', 'Bibliotecas')
    
